# Generated by Django 3.2.9 on 2022-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMC_no', models.CharField(max_length=10, unique=True)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Contact_no', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(blank=True, max_length=40, null=True)),
                ('Address', models.CharField(max_length=40)),
                ('Hospital_worked_at', models.CharField(max_length=30)),
                ('Specialist', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Contact_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=40)),
                ('Blood_group', models.CharField(max_length=20)),
            ],
        ),
    ]
